### ISSUE TITLE
how to do fluid-rendering part

### ISSUE THREAD

**Issue by Bariona** [Jukgei/CFD_Taichi#1]
Hi @Jukgei , I just ran the command 
```
python main.py
```
but it seems that the GUI interface only shows the particle-simulation process, how can I render it so that I can get the same gif result shown in your `README.md`? 

Thanks!

**Comment by Jukgei** [comment]
Hello @Bariona, thank you for your interest in this project. You can save the simulated particles in the PLY format and then use software like Blender or Houdini for rendering.
